# Generated by Django 6.0.7 on 2026-07-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacketUser',
            fields=[
                ('pkt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'packet_user',
                'ordering': ['pkt_id'],
            },
        ),
    ]
