# Generated by Django 6.0.7 on 2026-07-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamForm',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('registration_no', models.CharField(max_length=255)),
                ('admission_no', models.CharField(max_length=255)),
                ('enroll_no', models.CharField(max_length=255)),
                ('student_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('student_batch', models.IntegerField()),
                ('college_id', models.IntegerField()),
                ('college_name', models.CharField(max_length=255)),
                ('branch_id', models.IntegerField()),
                ('branch_name', models.CharField(max_length=255)),
                ('exam_type', models.CharField(max_length=255)),
                ('sch_id', models.IntegerField()),
                ('scheme_title', models.CharField(max_length=255)),
                ('sem_year', models.IntegerField()),
                ('exam_Form_Date', models.CharField(max_length=255)),
                ('source_file', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'exam_form',
                'ordering': ['roll_no'],
            },
        ),
    ]
