# Generated by Django 6.0.7 on 2026-07-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_examform'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('cont', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('acc', models.CharField(max_length=255)),
                ('ifsc', models.CharField(max_length=255)),
                ('inst', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bank_details',
                'ordering': ['name'],
            },
        ),
    ]
