# Generated by Django 6.0.7 on 2026-07-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bankdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubListEven202526',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.IntegerField()),
                ('course', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('sem', models.CharField(max_length=255)),
                ('paper_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('paper_code', models.CharField(max_length=255)),
                ('credits', models.CharField(max_length=255)),
                ('e_identity', models.CharField(max_length=255)),
                ('maximum_marks', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('dept_main', models.CharField(max_length=255)),
                ('e_email', models.CharField(max_length=255)),
                ('e_name', models.CharField(max_length=255)),
                ('e_institute', models.CharField(max_length=255)),
                ('e_contact', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
            ],
        ),
    ]
