# Generated by Django 6.0.7 on 2026-07-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sublisteven202526'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubListOdd202526',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=255)),
                ('e_institute', models.CharField(max_length=255)),
                ('e_email', models.CharField(max_length=255)),
                ('e_contact', models.CharField(max_length=255)),
                ('e_identity', models.CharField(max_length=255)),
                ('dept_main', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('sem', models.CharField(max_length=255)),
                ('paper_name', models.CharField(max_length=255)),
                ('paper_code', models.CharField(max_length=255)),
                ('time_allowed_mod', models.CharField(max_length=255)),
                ('maximum_marks', models.CharField(max_length=255)),
                ('level', models.CharField(db_column='Level', max_length=255)),
            ],
            options={
                'db_table': 'sublist_odd_202526',
                'ordering': ['e_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='sublisteven202526',
            options={'ordering': ['select']},
        ),
        migrations.AlterModelTable(
            name='sublisteven202526',
            table='sublist_even_202526',
        ),
    ]
