# Generated by Django 6.0.7 on 2026-07-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sublistodd202526_alter_sublisteven202526_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketPaymentDecember2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField(unique=True)),
                ('pkt_no', models.CharField(max_length=50)),
                ('pkt_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('dept', models.CharField(blank=True, max_length=200, null=True)),
                ('inst', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('cont', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=50)),
                ('qty', models.PositiveIntegerField()),
                ('bank', models.CharField(max_length=200)),
                ('account', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=20)),
                ('payment_stage', models.CharField(max_length=100)),
                ('payment', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Packet Payment',
                'verbose_name_plural': 'Packet Payments',
                'db_table': 'packet_payment',
                'ordering': ['sr_no'],
            },
        ),
        migrations.AlterModelOptions(
            name='bankdetails',
            options={'ordering': ['name'], 'verbose_name': 'Paper Setter and Evaluators Bank Details', 'verbose_name_plural': 'Paper Setter and Evaluators Bank Details'},
        ),
        migrations.AlterModelOptions(
            name='examform',
            options={'ordering': ['roll_no'], 'verbose_name': 'Students Exam Form Details', 'verbose_name_plural': 'Students Exam Form Details'},
        ),
        migrations.AlterModelOptions(
            name='packetuser',
            options={'ordering': ['pkt_id'], 'verbose_name': 'Packet id, user id and password', 'verbose_name_plural': 'Packet id, user id and password'},
        ),
        migrations.AlterModelOptions(
            name='sublisteven202526',
            options={'ordering': ['select'], 'verbose_name': 'Sub List Even 2025-26', 'verbose_name_plural': 'Sub List Even 2025-26'},
        ),
        migrations.AlterModelOptions(
            name='sublistodd202526',
            options={'ordering': ['e_name'], 'verbose_name': 'Sub List Odd 2025-26', 'verbose_name_plural': 'Sub List Odd 2025-26'},
        ),
    ]
