# Generated by Django 6.0.7 on 2026-07-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_packetpaymentdecember2025_alter_bankdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetpaymentdecember2025',
            name='sr_no',
            field=models.CharField(max_length=50),
        ),
    ]
