# Generated by Django 6.0.7 on 2026-07-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_packetpaymentdecember2025_sr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetpaymentdecember2025',
            name='pkt_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
