# Generated by Django 6.0.7 on 2026-07-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_packetpaymentdecember2025_pkt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetpaymentdecember2025',
            name='payment',
            field=models.CharField(),
        ),
    ]
