# Generated by Django 6.0.7 on 2026-07-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_packetpaymentdecember2025_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSetterDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institute', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(max_length=255)),
                ('paper_names', models.TextField(help_text='Comma-separated paper names / specialization')),
                ('active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paper Setter Database',
                'verbose_name_plural': 'Paper Setter Database',
                'db_table': 'paper_setter_database',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='packetpaymentdecember2025',
            options={'ordering': ['sr_no'], 'verbose_name': 'Packet Payment Odd 2025-26', 'verbose_name_plural': 'Packet Payment Odd 2025-26'},
        ),
        migrations.AlterModelOptions(
            name='packetuser',
            options={'ordering': ['pkt_id'], 'verbose_name': 'Packet id, user id and password', 'verbose_name_plural': 'Packet id, user id and password Even 2025-26'},
        ),
    ]
