# Generated by Django 6.0.7 on 2026-07-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_todotask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='completed',
        ),
    ]
