# Generated by Django 6.0.7 on 2026-07-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_todotask_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('other', 'Other')], default='Work', max_length=20),
        ),
    ]
