# Generated by Django 6.0.7 on 2026-07-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_todotask_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDateSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=120)),
                ('sem_year', models.PositiveSmallIntegerField(verbose_name='Semester / Year')),
                ('sub_code', models.CharField(max_length=50, verbose_name='Subject Code')),
                ('subj_title', models.CharField(max_length=255, verbose_name='Subject Title')),
                ('exam_date', models.DateField()),
                ('exam_starttime', models.TimeField(verbose_name='Exam Start Time')),
                ('student_strength', models.PositiveIntegerField(default=0)),
                ('centre_no', models.CharField(max_length=20, verbose_name='Centre No.')),
            ],
            options={
                'verbose_name': 'Exam Date Sheet Entry',
                'verbose_name_plural': 'Exam Date Sheet Entries',
                'ordering': ['exam_date', 'exam_starttime', 'centre_no', 'branch', 'sem_year', 'sub_code'],
            },
        ),
        migrations.AlterField(
            model_name='todotask',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('other', 'Other')], default='work', max_length=20),
        ),
    ]
