# Generated by Django 6.0.7 on 2026-07-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_examdatesheet_alter_todotask_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdatesheet',
            name='centre_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='examdatesheet',
            name='exam_starttime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='examdatesheet',
            name='sem_year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='examdatesheet',
            name='sub_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='examdatesheet',
            name='subj_title',
            field=models.CharField(max_length=255),
        ),
    ]
