# Generated by Django 6.0.7 on 2026-07-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_examdatesheet_centre_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PacketUser',
        ),
        migrations.AlterModelOptions(
            name='examdatesheet',
            options={'ordering': ['exam_date', 'exam_starttime', 'centre_no', 'branch', 'sem_year', 'sub_code'], 'verbose_name': 'Exam Date Sheet May 2026', 'verbose_name_plural': 'Exam Date Sheet May 2026'},
        ),
        migrations.AlterModelOptions(
            name='examform',
            options={'ordering': ['roll_no'], 'verbose_name': 'z Students Exam Form Details', 'verbose_name_plural': 'z Students Exam Form Details'},
        ),
    ]
